---
- name: Include vars
  include_vars: vars/packages.yml

- name: Install shared libraries
  yum: name={{ item }}
  with_items: "{{ shared_libraries }}"

- name: Setup repo
  copy: content="options(repos = c(CRAN = 'https://cran.rstudio.com'))" dest=~/.Rprofile
  become: no

- name: Install r
  yum: name=r-cran-littler

- name: Get R_LIBS_USER
  command: /usr/bin/r -e 'cat(Sys.getenv("R_LIBS_USER"))'
  become: no
  register: r_libs_user

- name: Create directory for user libraries
  file: path={{ r_libs_user.stdout }} state=directory
  become: no

- name: Install docopt
  command: /usr/bin/r --libpath={{ r_libs_user.stdout }} -e 'if(! "docopt" %in% installed.packages()) install.packages("docopt")'
  become: no

- name: Install R packages from CRAN
  script: scripts/install.r "{{ cran_packages | join(' ') }}"
  become: no

- name: Install R packages from Github
  command: "/usr/lib/R/site-library/littler/examples/installGithub.r {{ github_packages | join(' ') }}"
  become: no
  when: github_packages is defined
