---
- hosts: all
  become: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - base
    - ssh-keygen
    - java
    # - scala

    
- hosts: spark-master
  become: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - {role: "hadoop", hadoop_is_namenode: "true"}


- hosts: slaves
  become: yes
  vars_files:
    - ./vars/base-env.yml
  roles:
    - {role: "hadoop", hadoop_is_datanode: "true"}

# - hosts: spark-master
#   become: yes
#   vars_files:
#     - ./vars/base-env.yml
#   roles:
#     - {role: "spark", spark_is_master: "true"}

# - hosts: slaves
#   become: yes
#   vars_files:
#     - ./vars/base-env.yml
#   roles:
#     - {role: "spark", spark_is_slave: "true"}

# - hosts: spark_master
#   become: yes
#   vars_files:
#     - ./vars/base-env.yml
#   roles:
#     - r
#     - rstudio
    
# - hosts: slave
#   tasks:
#     - name: create .ssh folder
#       file:
#         path: "{{ user_home }}/.ssh"
#         state: directory
#         mode: 0700
#         owner: "{{ my_user }}"
#         group: "{{ my_group }}"

#     - name: copy ssh key    
#       copy:
#         src: "{{ item }}"
#         dest: "{{ user_home }}/.ssh"
#         owner: "{{ my_user }}"
#         group: "{{ my_group }}"
#         mode: 0600
#         with_items:
#           - id_rsa
#           - id_rsa.pub
#           - authorized_keys

# - hosts: slave
#   tasks:
#     - name: Set authorized key for user vagrant copying it from current user
#       authorized_key:
#         user: vagrant
#         state: present
#         key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
