---
# defaults file for spark2
spark_download_url:
 "https://mirrors.tuna.tsinghua.edu.cn/apache/spark/spark-{{spark_version}}/spark-{{spark_version}}-bin-hadoop{{hadoop_version}}.tgz"
spark_tar_name: "spark-{{spark_version}}-bin-hadoop{{hadoop_version}}.tgz"
# hadoop_native_lib_url: "https://bintray.com/sequenceiq/sequenceiq-bin/download_file?file_path=hadoop-native-64-2.6.0.tar"
hadoop_native_version: "{{hadoop_version}}.0"
hadoop_native_tar: "hadoop-native-64-{{hadoop_native_version}}.tar"
hadoop_native_lib_url: "http://dl.bintray.com/sequenceiq/sequenceiq-bin/:{{hadoop_native_lib}}"
