---
- stat: path="/usr/lib/jvm/{{jdk8_version_name}}/bin/java"
  register: jvm


- name: mkdir for Java
  file:
    path="/usr/lib/jvm/"
    state=directory
    mode="u=rwx,go=rx"
  when: not jvm.stat.exists

  
- name: "Copy {{jdk8_tar_name}}"
  copy:
    src="{{jdk8_tar_path}}"
    dest="{{user_home}}"
  when: not jvm.stat.exists


- name: install JDK
  unarchive:
    src="{{user_home}}/{{jdk8_tar_name}}"
    dest="/usr/lib/jvm/"
    mode="go-w"
    copy=no
  when: not jvm.stat.exists

  
- file:
    src="/usr/lib/jvm/{{jdk8_version_name}}"
    dest="{{JAVA_HOME}}"
    state=link
  when: not jvm.stat.exists

  
- name: set JAVA_HOME
  lineinfile:
    dest='/etc/profile'
    line='export JAVA_HOME={{JAVA_HOME}}'
    state=present
  when: not jvm.stat.exists

  
- lineinfile:
    dest='/etc/profile'
    line='export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar'
    state=present
  when: not jvm.stat.exists

  
- lineinfile:
    dest='/etc/profile'
    line='export PATH="$PATH:$JAVA_HOME/bin"'
    state=present
  when: not jvm.stat.exists
  
