---
- name: Strict host key checking no
  blockinfile:
    backup: yes
    dest: /etc/ssh/ssh_config
    block: |
      StrictHostKeyChecking no

- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: no
  
- name: Update packages
  yum:
    name: '*'
    state: latest

- name: add /sbin to path
  lineinfile: dest="/etc/profile" line="PATH=/sbin/:$PATH"
    
- name: Update host
  blockinfile:
    backup: yes
    dest: "/etc/hosts"
    block: |
      {{ hosts }}

- name: Install softwares
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - unzip
    - tar
    - openssh-server
